PyCUB: Machine exploration of the Codon Usage Bias: PyCUB.homoset.HomoSet Class Reference
PyCUB.homoset.HomoSet Class Reference
HomoSet is the object containing evrey homology as a dictionnary according to thie rhomology code.
Public Member Functions
def __init__ (self, kwargs)
will initialize the object with the different values you might have from another project use the data dictionnary to add any type of data
def __getitem__ (self, key)
get the homology at the corresponding key
def __setitem__ (self, key, value)
add an item at the corresponding key
def __delitem__ (self, key)
def __iter__ (self)
def iteritems (self)
def __len__ (self)
def update (self, val)
a function to update the dictionnary that homoset is
def plot_all (self, With='tsne', perplexity=60, interactive=False, bins=100, offset=20, iteration=400, redo=False, bypasstsne=False, dotsize=7, inpar=True)
will plot all the homologies in the full_homo_matrix (and compute it)
def loadfullhomo (self)
function to concatenate all the homologies in one big array(practicle for certain computations)
def loadhashomo (self, withnames=False)
function to compute the matrix of bool saying wether species X has a gene or more in homology Y
def size (self)
the size of the homoset (number of genes)
def add_random_homology (self)
a function to populate a homology with random values
def preprocessing (self, withtaxons=False, withnames=True)
will compute the full list of names,
def preprocessing_taxons (self)
def preprocessing_names (self)
same as preprocessing_taxons() but admiting there is no taxon information (Yun's data for example)
def preprocessing_namelist (self)
same as preprocessing_names() but without preprocessing the names of each homologies only updating the species_namelist
def compute_ages (self, preserved=True, minpreserv=0.9, minsimi=0.85)
will compute whether or not a coding gene is highly preserved and if not how recent it is
def compute_entropyloc (self, using='computejerem')
called if need entropy location and used ensembl data.
def remove (self, species)
remove this list of species from the homologies
def clean_species (self, thresh=0.3)
will remove a species from all the homologies of this homoset
def plot_homoperspecies (self)
will plot the number of homology per spcies in this homology group
def plot_speciesperhomo (self)
will plot the number of species per homologies in this homology group
def cluster_homologies (self, clustering='kmeans', byspecie=False, order=True, plot_ordering=True, homogroupnb=2, findnb=False)
Compute an homology group :
def orderfromclust (self, homogroupnb, clust, byspecie=False, plot_ordering=True)
creates an ordering of every elements
def get_clusterstats (self, sort=True, interactive=True, redo=False)
will find the number of cluster i per homologies and per species
def compare_clusters (self, cubdistance_matrix=True, plot=True, interactive=True, size=40)
for each clusters in homologies, will compare them with a similarity matrix and a distance matrix
def find_clusters (self, clustering='dbscan', homogroupnb=None, assess=True, eps=0.8, best_eps=True, trainingset=30, epoch=20, ranges=[0.2, size=10, redo=False)
Finds, for each homologies in the working homoset, groups that are part of compact clusters.
def findbest_eps (self, trainingset=400, clustering="dbscan", epoch=20, ranges=[0.2, size=10, redo=False)
will find the best eps hyperparameter (the one that minimizes the evolutionary distance within its clusters)
def plot_hashomo (self, invert=False, size=40, interactive=False, rangeto=None)
plot the has homo matrix
def plot_simiclust (self, interactive=True, size=40)
plot the similarity matrix of each homologies from its clusters
def plot_distcub (self, interactive=False, size=40)
plot the distance matrix of each homologies from the average of their CUB distances
Public Attributes
homo_namelist
species_namelist
homogroupnb
clusters
datatype
phylo_distances
best_eps
wasclusterized
stats
homodict
cluster_similarity
cub_similarity
Static Public Attributes
hashomo_matrix = None
homo_matrix = None
homo_matrixnames = None
fulleng = None
dictionary homodict = {}
list homo_namelist = []
list species_namelist = []
list clusters = []
int homogroupnb = 2
red_homomatrix = None
bool wasclusterized = False
homo_clusters = None
string datatype = ''
averagehomo_matrix = None
dictionary stats = {}
Private Member Functions
def _barplot (self, interactive=True)
called by statistics function to plot a barplot of the proportion of different cluster per homologies and per species
def _dictify (self, savehomos=False)
Used by the saving function.
def _plot_clust (self, mat, orderedmat)
will plot the correlation matrix of the has_homomatrix before and after ordering allowing one to show its effect
Detailed Description
HomoSet is the object containing evrey homology as a dictionnary according to thie rhomology code.
from Homoset you can do much computation that requires the set of homologies Object where we store an homology group basically where we do our entire Computation from. Be aware that even if you use str, the keys will be stored as unicode as jsonized dict will output unicode in python < 3
Parameters
hashomo_matrix a np.array[boolean] (species, homologies) that store the matrix of gene presence in species
homo_matrix np.array[float] (homologies*species(inthehomologies),aminoacids) but containing the codon entropy vectors instead
homodict dictionnary of homology object containing codon usage per species for the gene coresponding to this homology
homo_namelist list[str] of all the homology names
species_namelist list[str] of all the species names
clusters list[int] of clusters for the homoset clustering can be of size of nb of species or of nb of homologies
homogroupnb int of group for the homology clustering
red_homomatrix np.array[float] (homologies*species(inthehomologies),x*y)the reduced 2D version of the homology matrix for the full homology matrix
wasclusterized bool if the homologies have been clustered or not. usefull for processing requiring clusters
homocluster np.array[int] homologies*species of int of cluster number
homo_matrixnames np.array[int] corresponding to names in PyCUB.utils.speciestable
fulleng np.array[int] number of coding for each amino for each gene for each homology
datatype str of the CUB value type [entropy, A_value(entropyLocation), frequency]
averagehomo_matrix np.array[float] of the avg CUB values per homologies
stats dict of statistics on the clusterings (see get_clusterstats())
Constructor & Destructor Documentation
__init__()
def PyCUB.homoset.HomoSet.__init__ (self, kwargs)
will initialize the object with the different values you might have from another project use the data dictionnary to add any type of data
a dictionary to any values present in the homoset
Member Function Documentation
__getitem__()
def PyCUB.homoset.HomoSet.__getitem__ (self, key)
get the homology at the corresponding key
Parameters
key str, unicode the key at which to get the homology
        TypeError "the type you should enter is int or unicode or str"
Exceptions
KeyError
Referenced by PyCUB.homoset.HomoSet.__init__().
__setitem__()
def PyCUB.homoset.HomoSet.__setitem__ (self, key, value)
add an item at the corresponding key
Parameters
key str, unicode the key at which to add
val PyCUB.homology to add at this key
        TypeError "the type you should enter is int or unicode or str"
Exceptions
KeyError
Referenced by PyCUB.homoset.HomoSet.__getitem__().
_barplot()
def PyCUB.homoset.HomoSet._barplot (self, interactive = True) private
called by statistics function to plot a barplot of the proportion of different cluster per homologies and per species
Parameters
interactive bool to true if you want to use the bokeh interactive version
Returns
the barplot holoviews object (will directly render if in a notebook)
Referenced by PyCUB.homoset.HomoSet.findbest_eps(), and PyCUB.homoset.HomoSet.get_clusterstats().
_dictify()
def PyCUB.homoset.HomoSet._dictify (self, savehomos = False) private
Used by the saving function.
transform the object into a dictionary that can be json serializable
Parameters
savehomos bool to true if you consider this homology as containing all the information (the other ones only have references to a subset of the data of this one)
Returns
the dictionnary of all the data in this Object in the correct format to be jsonized
Referenced by PyCUB.homoset.HomoSet._barplot(), and PyCUB.pyCUB.PyCUB.save().
_plot_clust()
def PyCUB.homoset.HomoSet._plot_clust (self, mat, orderedmat) private
will plot the correlation matrix of the has_homomatrix before and after ordering allowing one to show its effect
Parameters
mat np.array[bool] the current homology matrix
orderedmat np.array[bool] the ordered homology matrix
Referenced by PyCUB.homoset.HomoSet.orderfromclust(), and PyCUB.homoset.HomoSet.plot_distcub().
add_random_homology()
def PyCUB.homoset.HomoSet.add_random_homology (self)
a function to populate a homology with random values
Parameters
None
Returns
the name of the random homology (str)
Referenced by PyCUB.homoset.HomoSet.size().
clean_species()
def PyCUB.homoset.HomoSet.clean_species (self, thresh = 0.3)
will remove a species from all the homologies of this homoset
Warning, as the all/working homosets share the ref to homologies, deleting some species in working_homoset will result in removing some species in some homologies of all_homoset
Parameters
thresh float the threshold of avg presence in homologies below which the species are remove
Referenced by PyCUB.homoset.HomoSet.remove().
cluster_homologies()
def PyCUB.homoset.HomoSet.cluster_homologies (self, clustering = 'kmeans', byspecie = False, order = True, plot_ordering = True, homogroupnb = 2, findnb = False)
Compute an homology group :
from matrix computation using the homo_matrix (or from network computation in homologize_from_network) Can be computed many times and will updata homoset with the most recent homoset found if homoset exists, it will save it.
Parameters
clustering str flags to 'kmeans', 'kmodes', 'fast' to use different sk-learn algorithms
plot bool flags to true for the function to output ploting of the affinity matrix with and without the clusters
homogroupnb int nb of groups you want to extract
byspecie bool to true if we cluster by species instead of homologies
order bool whether or not to order
plot_ordering bool to true to plot this ordering
findnb bool to true to find the right number of clusters (homogroupnb)
Returns
if findnb, will return the clusters for each homogroupnb up to 9
Exceptions
AttributeError "you entered a wrong clustering algorithm"
Referenced by PyCUB.homoset.HomoSet.plot_speciesperhomo().
compare_clusters()
def PyCUB.homoset.HomoSet.compare_clusters (self, cubdistance_matrix = True, plot = True, interactive = True, size = 40)
for each clusters in homologies, will compare them with a similarity matrix and a distance matrix
compare amongst the working homoset homologies, the clusters together, by what species they contains by creating a new vector of species presence in each cluster and plotting the similarity matrix of each of those vectors. –> create a compare function in homoset of homologies clusters similarity matrix and ordering. basically the distance should be nan if it has not the species, -1 if outlier to other and 1 if one cluster to another and zeros if the same to the same
Parameters
cubdistance_matrix bool to true if want to compute the matrix of the averageCUB value distances summed for each cluster amongst the homologies
plot bool to true to plot
size int the size of the plot
Referenced by PyCUB.homoset.HomoSet.get_clusterstats().
compute_ages()
def PyCUB.homoset.HomoSet.compute_ages (self, preserved = True, minpreserv = 0.9, minsimi = 0.85)
will compute whether or not a coding gene is highly preserved and if not how recent it is
it uses the phylogenetic distances and the similarities amongst homlogies to try to find a good proxy
Parameters
preserved bool to true if we should find highly preserved genes or not
minpreserv float minimal percentage of homologous species that have this homology
minsimi float minimal avg similarity between genes to consider them highly preserved
Exceptions
UnboundLocalError "you need to have the similarity_scores"
Referenced by PyCUB.homoset.HomoSet.preprocessing_namelist().
compute_entropyloc()
def PyCUB.homoset.HomoSet.compute_entropyloc (self, using = 'computejerem')
called if need entropy location and used ensembl data.
you can always compute entropy location from entropy data.
   Will be much faster than doing it directly when calling
   ensembl's data as it computes the partition function
   only one for each lengths
Parameters
using str flags the partition algorithm to use
Exceptions
UnboundLocalError "you need to have your CUB values as entropy"
Referenced by PyCUB.homoset.HomoSet.compute_ages().
find_clusters()
def PyCUB.homoset.HomoSet.find_clusters (self, clustering = 'dbscan', homogroupnb = None, assess = True, eps = 0.8, best_eps = True, trainingset = 30, epoch = 20, ranges = [0.2, size = 10, redo = False)
Finds, for each homologies in the working homoset, groups that are part of compact clusters.
it will be using gaussian mixture clustering or DBSCAN and order them according to the density of each cluster (we are interested in the densest ones) and assess the quality using 3 criterion:BIC, number of outliers, also find if we are close to ancestry tree, here we need to represent a comparison of the closeness in a phylogenetic tree to a cluster of species –> given a grouping of phylogenetic tree, what cluster is the most similar to it
Parameters
clustering method (DBSCAN, gaussian mixture)
homogroupnb the number of groups can be a number or else will look for the better number of cluster according to assessments.
assess plot or not the assessments
eps the hyperparams
best_eps bool to true wether or not to do an hyperparam greedy search
trainingset int if best_eps, the size of the training ser
epoch int the number of increasing trials
ranges tuple[float] the two min and max values to use
size int the x size of the plot
Referenced by PyCUB.homoset.HomoSet.compare_clusters().
findbest_eps()
def PyCUB.homoset.HomoSet.findbest_eps (self, trainingset = 400, clustering = "dbscan", epoch = 20, ranges = [0.2, size = 10, redo = False)
will find the best eps hyperparameter (the one that minimizes the evolutionary distance within its clusters)
Parameters
trainingset int the number of homologies in your training set (should be 20% of the total)
clustering str flags the clustering algorithm from which to find the best hyperparam
epoch int the number of increasing trials
ranges tuple[float] the two min and max values to use
size int the x size of the plot
redo wether or not to recompute everyhting if it has already been computed once
Returns;
the best value (often a float)
Exceptions
LookupError "you need to compute the phylogenetic distances first to have some form of labels"
Referenced by PyCUB.homoset.HomoSet.find_clusters().
get_clusterstats()
def PyCUB.homoset.HomoSet.get_clusterstats (self, sort = True, interactive = True, redo = False)
will find the number of cluster i per homologies and per species
plot for each species, how much its genes are outliers, how much are belonging to a secondary cluster and how much are belonging to the principal cluster. –> create a long stacked bar plot with these values
Parameters
sort bool to true to sort everyhting according to the statistics differences
interactive bool to true to have an interactive barplot
redo bool to true not to reused cached data
Exceptions
UnboundLocalError "you need to find clusters first"
Referenced by PyCUB.homoset.HomoSet.orderfromclust().
loadfullhomo()
def PyCUB.homoset.HomoSet.loadfullhomo (self)
function to concatenate all the homologies in one big array(practicle for certain computations)
Parameters
None
Referenced by PyCUB.homoset.HomoSet.compute_entropyloc(), and PyCUB.homoset.HomoSet.plot_all().
loadhashomo()
def PyCUB.homoset.HomoSet.loadhashomo (self, withnames = False)
function to compute the matrix of bool saying wether species X has a gene or more in homology Y
Parameters
None
Referenced by PyCUB.homoset.HomoSet.loadfullhomo(), and PyCUB.homoset.HomoSet.size().
orderfromclust()
def PyCUB.homoset.HomoSet.orderfromclust (self, homogroupnb, clust, byspecie = False, plot_ordering = True)
creates an ordering of every elements
(names, homologies according to the found clusters) from an ordered cluster of species or of homologies self.hashomomatrix should reflect this orientation as well
Parameters
homogroupnb int the number of clusters
clust np.array(int) the clusters
byspecie bool to true to order by species
plot_ordering bool to true to plot the ordering
Returns
the ordered hashomomatrix (np.array[bool])
Referenced by PyCUB.homoset.HomoSet.cluster_homologies().
plot_all()
def PyCUB.homoset.HomoSet.plot_all (self, With = 'tsne', perplexity = 60, interactive = False, bins = 100, offset = 20, iteration = 400, redo = False, bypasstsne = False, dotsize = 7, inpar = True)
will plot all the homologies in the full_homo_matrix (and compute it)
(sometimes around 800 000 datapoints) to look at any kind of relationships as there is too much datapoints, the plots are density ones.
Parameters
With flag the dim reduction algorithm to use (tsne: need >16gigs of RAM,now use another version of tsne for large datasets)(PCA: works well)(lsta/hessian:untested)
perplexity ints of basic tsne hyperparams
interactive bool if true should use bokeh else matplotlib
Returns
the desired plot if the size is high and we are interactive
Exceptions
AttributeError "not a good red algorithm"
Referenced by PyCUB.homoset.HomoSet.update().
plot_distcub()
def PyCUB.homoset.HomoSet.plot_distcub (self, interactive = False, size = 40)
plot the distance matrix of each homologies from the average of their CUB distances
the interactive version allows you to see each particular datapoint with much more precision
Parameters
interactive bool to use the bokeh interactive version
size size of the matrix
Referenced by PyCUB.homoset.HomoSet.compare_clusters(), and PyCUB.homoset.HomoSet.plot_simiclust().
plot_hashomo()
def PyCUB.homoset.HomoSet.plot_hashomo (self, invert = False, size = 40, interactive = False, rangeto = None)
plot the has homo matrix
the interactive version allows you to see each particular datapoint with much more precision
Parameters
interactive bool to use the bokeh interactive version
size int size of the matrix
invert bool flag to true to invert the plot
Referenced by PyCUB.homoset.HomoSet._dictify().
plot_simiclust()
def PyCUB.homoset.HomoSet.plot_simiclust (self, interactive = True, size = 40)
plot the similarity matrix of each homologies from its clusters
the interactive version allows you to see each particular datapoint with much more precision
Parameters
interactive bool to use the bokeh interactive version
size size of the matrix
Referenced by PyCUB.homoset.HomoSet.compare_clusters(), and PyCUB.homoset.HomoSet.plot_hashomo().
preprocessing()
def PyCUB.homoset.HomoSet.preprocessing (self, withtaxons = False, withnames = True)
will compute the full list of names,
find doublons, and set the names to ints instead of strings. called after loading from ensembl and associate namelist in each homologies to a number in utils.speciestable
Parameters
withtaxons bool to true calls preprocessing_taxons() else one of the other two
withnames bool to true to call preprocessing_names() else calls preprocessing_namelist()
Returns
taxons list, if the names contains an additional list of taxon ids. and the corresponding species in the same order only if withtaxons
Referenced by PyCUB.homoset.HomoSet.add_random_homology().
preprocessing_namelist()
def PyCUB.homoset.HomoSet.preprocessing_namelist (self)
same as preprocessing_names() but without preprocessing the names of each homologies only updating the species_namelist
Parameters
None
Referenced by PyCUB.homoset.HomoSet.preprocessing(), and PyCUB.homoset.HomoSet.preprocessing_names().
preprocessing_names()
def PyCUB.homoset.HomoSet.preprocessing_names (self)
same as preprocessing_taxons() but admiting there is no taxon information (Yun's data for example)
Parameters
None
Referenced by PyCUB.homoset.HomoSet.preprocessing().
remove()
def PyCUB.homoset.HomoSet.remove (self, species)
remove this list of species from the homologies
Parameters
species list[str] the species to remove from all homologies
Referenced by PyCUB.homoset.HomoSet.clean_species(), and PyCUB.homoset.HomoSet.compute_entropyloc().
size()
def PyCUB.homoset.HomoSet.size (self)
the size of the homoset (number of genes)
Parameters
None
Returns
int the number of genes
Referenced by PyCUB.homoset.HomoSet.loadhashomo().
update()
def PyCUB.homoset.HomoSet.update (self, val)
a function to update the dictionnary that homoset is
Parameters
val the dict to append tot this one
Referenced by PyCUB.homoset.HomoSet.__init__(), PyCUB.homoset.HomoSet.__setitem__(), and PyCUB.homoset.HomoSet.add_random_homology().
The documentation for this class was generated from the following file:
PyCUB/homoset.py