PyCUB: Machine exploration of the Codon Usage Bias: PyCUB.pyCUB.PyCUB Class Reference
PyCUB.pyCUB.PyCUB Class Reference
PyCUB is the main object of the project that allows the user to access most of the functions.
Public Member Functions
def __init__ (self, species={}, _is_saved=False, _is_loaded=False, working_homoset=None, all_homoset=None, session='session1')
will initialize the object with the different values you might have from another project
def getHomologylist (self, species='saccharomyces_cerevisiae', kingdom='fungi')
A function to retrieve the homologies directly from a given species.
def get_data (self, From='yun', homonames=None, kingdom='fungi', sequence='cdna', additional='type=orthologues', saveonfiles=False, normalized=True, setnans=False, by="entropy", using="normal", tRNA=True, getCAI=True, first=20, inpar=True)
Download the data from somewhere on the web (Ensembl, Yun(with links))
def get_metadata_Ensembl (self, kingdoms)
download it and put it where it belongs in the Espece object
def get_mymetadata (self, From='jerem', inpar=True)
Go ahead and design your own metadata retrieval here.
def import_metadataTobias (self)
will import the metadata obtained from tobias for the fungi species affiliated to cerevisiae to each species for further diagnostics.
def load (self, session=None, All=False, filename='first500', From=None, by='entropy', tRNA=True, inpar=True)
Get the data that is already present on a filename.
def loadmore (self, filename='first500', by='entropyLocation')
Get the data that is already present on a filename when you already have data.
def save (self, name, save_workspace=True, save_homo=True, add_homosets={}, cmdlinetozip="gzip")
call to save your work.
def get_working_homoset (self, clusternb=None, species=None, homologies=None, cleanhomo=None)
create a subset of all_homoset on which you would like to do further computation
def get_subset (self, homoset, withcopy=False, clusternb=None, species=None, homologies=None)
either changes or returns a subset of the provided homoset
def get_full_genomes (self, kingdom='fungi', seq='cds', avg=True, by="entropy", normalized=False)
go trought all full genome fasta files in the ftp server of ensemblgenomes and
def get_taxons (self)
find the taxons of each referenced species (see PyCUB.Espece.gettaxons())
def get_evolutionary_distance (self, display_tree=False, size=40)
uses metadata of the ancestry tree and computes a theoretical evolutionary distance matrix between each species
def createRefCAI (self, speciestocompare='saccharomyces_cerevisiae', kingdom='fungi', first=20)
do a compute CAI
def speciestable (self)
a copy of the utils.speciestable
def phylo_distances (self)
a copy of the phylodistances dataframe see (get_evolutionary_distance())
def compute_averages (self, homoset)
compute the average entropy
def compare_species (self, showvar=True, reducer='tsne', perplexity=40, eps=0.3, size=10)
compare the species according to their mean CUB,
def compute_ages (self, homoset, preserved=True, minpreserv=0.9, minsimi=0.85)
def regress_on_species (self, without=[""], full=True, onlyhomo=False, perctrain=0.8, algo="lasso", eps=0.001, n_alphas=100)
Will fit a regression curve on the CUB values of the different species according to the metadatas available for each of them.
def compare_homologies (self, homoset, homosapiens=False, mindistance=10, preserved=True, size=10, minpreserv=0.9, minsimi=0.9, showvar=True, eps=0.28, reducer='tsne', perplexity=40)
finds for species with a common ancester separated by a pseudo phylogenetic distance X,
def regress_on_genes (self, homoset, full=True, without=['meanecai', meancai, perctrain=0.8, algo="lasso", eps=0.001, n_alphas=100)
Will fit a regression curve on the CUB values of the different homologies according to the metadatas available for each of them.
def getRelation2G3DD (self, species_name='saccharomyces_cerevisiae', kingdom='fungi', intrachromosome="utils/meta/3Dmodel/interactions_HindIII_fdr0.01_intra_cerevisiae.csv", interchromose=["utils/meta/3Dmodel/cerevisiae_inter1.csv", utils, meta, Dmodel, cerevisiae_inter2, csv, utils, meta, Dmodel, cerevisiae_inter3, csv, utils, meta, Dmodel, cerevisiae_inter4, csv, utils, meta, Dmodel, cerevisiae_inter5, csv, bins=2000, seq='cds', use='diament2')
https://www.nature.com/articles/ncomms6876
def plot_distances (self, size=40)
plot the phylogenetic distance matrix
def loadspeciestable (self)
short function to retrieve the speciestable from Disk
def savespeciestable (self)
short function to put the speciestable on Disk
Public Attributes
species
homolist
pent
pcub
pcuf
Static Public Attributes
dictionary links
dictionary species = {}
working_homoset = None
all_homoset = None
session = None
coeffgenes = None
scoregenes = None
scorespecies = None
coeffspecies = None
Private Member Functions
def _dictify (self, save_workspace, save_homo, add_homosets)
Used by the saving function.
def _undictify (self, data)
same function but to retransform everything
Private Attributes
_is_saved
_is_loaded
Static Private Attributes
bool _is_saved
Detailed Description
PyCUB is the main object of the project that allows the user to access most of the functions.
When using it, please follow the documentation and examples on notebooks thought you can still use it as you please and use some of the nice tricks provided here and in python
Parameters
species dictionary of Espece objects from the name of the species. (see espece.py)
working_homoset PyCUB.homoset object that stores a subset of the homologies you want to work on all_homoset PyCUB.homoset that stores the all the homologies
session str the session name you want to use (will appear in the savings for example
_is_saved bool trivial system only boolean
links dict of all the links readily available in PyCUB. for the project of Jeremie KALFON please use whatever datasets you may find usefull (you can also download from Ensembl)
coeffgenes np.array regressing values for each attributes
scoregenes the score of the regressor
scorespecies the score of the regressor
coeffspecies np.array regressing values for each attributes
Constructor & Destructor Documentation
__init__()
def PyCUB.pyCUB.PyCUB.__init__ (self, species = {}, _is_saved = False, _is_loaded = False, working_homoset = None, all_homoset = None, session = 'session1')
will initialize the object with the different values you might have from another project
Parameters
species dictionary of Espece objects from the name of the species. (see espece.py)
working_homoset PyCUB.homoset object that stores a subset of the homologies you want to work on all_homoset PyCUB.homoset that stores the all the homologies
session str the session name you want to use (will appear in the savings for example
_is_saved bool trivial system only boolean
Member Function Documentation
_dictify()
def PyCUB.pyCUB.PyCUB._dictify (self, save_workspace, save_homo, add_homosets) private
Used by the saving function.
transform the workspace object into a dictionary that can be json serializable
   adding some params because else the object may be too big
Parameters
save_workspace bool to save working_homoset
save_homo bool to save all_homoset
ass_homosets PyCUB.homoset instances to add to this dict
Return
A dict holding every element to be jsonized
Referenced by PyCUB.pyCUB.PyCUB.plot_distances(), and PyCUB.pyCUB.PyCUB.save().
_undictify()
def PyCUB.pyCUB.PyCUB._undictify (self, data) private
same function but to retransform everything
Here we don't use other classes undictify functions but we just recreate them by passing it to their init methods which is clearer.
Parameters
data dict to undictify into the workspace object
Returns
Other PyCUB.homosets that would have been saved as add_homosets
Referenced by PyCUB.pyCUB.PyCUB._dictify(), and PyCUB.pyCUB.PyCUB.load().
compare_homologies()
def PyCUB.pyCUB.PyCUB.compare_homologies (self, homoset, homosapiens = False, mindistance = 10, preserved = True, size = 10, minpreserv = 0.9, minsimi = 0.9, showvar = True, eps = 0.28, reducer = 'tsne', perplexity = 40)
finds for species with a common ancester separated by a pseudo phylogenetic distance X,
genes/functions that are novel to only a subset. plot the two with their differences the differences between the two also considers an homology as highly preserved if it is shared amongst most of the species and if the average similarity score is high amongst this homology. also shows if there is a relationship between the number of amino acids the sequence does not encode for and the codon usage bias We could have used the sequence dating of ensembl but it only works for homo sapiens for now maybe use it for homosapiens later
Parameters
homosapiens bool to true if we should use homosapiens dataset on gene dates
mindistance int the minimal phylogenetic distance between in average in this homology to consider it highly conserved
preserved bool to true if we should find highly preserved genes or not
size the average size of the datapoints in the pointcloud representation of this dataset
minpreserv float minimal percentage of homologous species that have this homology
minsimi float minimal avg similarity between genes to consider them highly preserved
showvar bool to true, show the mean variance in CUB values accros this homology as a variation in dot sizes
eps float the hyperparamter of the clustering algorithm applied to this dataset
homoset PyCUB.homoset the homoset to use
reducer str the reducer to use 'tsne' or 'PCA'
perplexity int the perplexity hyperparam for tSNE
Exceptions
UnboundLocalError "you need to compute the averages of the all_homoset. use PyCUB.compute_averages(homoset)"
Referenced by PyCUB.pyCUB.PyCUB.regress_on_species().
compare_species()
def PyCUB.pyCUB.PyCUB.compare_species (self, showvar = True, reducer = 'tsne', perplexity = 40, eps = 0.3, size = 10)
compare the species according to their mean CUB,
plot the mean CUB to their full CUB, to their tRNA copy numbers, to the euclidean distance of their CUB to the one of their phylogenetic matrix. in this plot, the mean entropy value is plotted as a regular homology plot but each dot is a species thus we can compare them together, moreover, the size of the dots informs oneself of the variance in entropy per species. the color intensity informs on how much this is close to what is given by the tRNA values. (additional information such as name of the species, number of tRNA values,metadata and the point from its tRNA value is plotted when hovering the dot) then we can also compare the mean of homologies or else, the full entropy of the cdna sequence per species is also computed the euclidean distance amongst the species for the full entropy to see if a difference can be linked to some evolutionary for one codon
Parameters
size the average size of the datapoints in the pointcloud representation of this dataset
showvar bool to true, show the mean variance in CUB values accros this homology as a variation in dot sizes
eps float the hyperparamter of the clustering algorithm applied to this dataset
homoset PyCUB.homoset the homoset to use
reducer str the reducer to use 'tsne' or 'PCA'
perplexity int the perplexity hyperparam for tSNE
Exceptions
UnboundLocalError "you need to compute the averages of the all_homoset. use PyCUB.compute_averages(homoset)"
UnboundLocalError "you have to compute tRNA values, use PyCUB.get_tRNAcopy()"
AttributeError "try avg or full"
Referenced by PyCUB.pyCUB.PyCUB.compute_averages().
compute_averages()
def PyCUB.pyCUB.PyCUB.compute_averages (self, homoset)
compute the average entropy
Will add species related averages gotten from this homoset in the species container, and in the homoset everytime you compute averages from a set, they will get erased !
Parameters
homoset PyCUB.homoset from which to compute the averages
Referenced by PyCUB.pyCUB.PyCUB.speciestable().
createRefCAI()
def PyCUB.pyCUB.PyCUB.createRefCAI (self, speciestocompare = 'saccharomyces_cerevisiae', kingdom = 'fungi', first = 20)
do a compute CAI
where we get Tobias' data to find highly expressed genes and use them to compute codon frequency for the reference set and use it to compute the CAI and mean CAI for each ho mology.
Parameters
speciestocompare str the name of the species to retrieve the genes from
kingdom str the kingdom where we can find it
first the number of highly expressed genes to retrieve
Referenced by PyCUB.pyCUB.PyCUB.get_data(), and PyCUB.pyCUB.PyCUB.get_evolutionary_distance().
get_data()
def PyCUB.pyCUB.PyCUB.get_data (self, From = 'yun', homonames = None, kingdom = 'fungi', sequence = 'cdna', additional = 'type=orthologues', saveonfiles = False, normalized = True, setnans = False, by = "entropy", using = "normal", tRNA = True, getCAI = True, first = 20, inpar = True)
Download the data from somewhere on the web (Ensembl, Yun(with links))
you can provide a lot of different values to scrape Ensembl's datasets it will compute from ensembl to retrieve a similar dataset as what yun's data is.
Parameters
From str flag 'yun' or 'ensembl':
homonames list[str] what particular homologies you want to scrap if 'all' and you have used the getHomologylist() function, will get the homologies from there
kingdom str same for kingdoms
sequence str the type of sequences you want to use
additional str additional information about the scrapping
saveonfiles bool save the unprocessed data before populating working homoset
normalized bool if you want the values to be normalized by the length of the codons (lengths are always saved)
setnans bool if you want to save the nans as metadata
by str flag 'entropy', 'entropyLocation' (entropy location), 'frequency'
using str flag 'random' 'normal' 'permutation' 'full'
inpar bool or int for parallel computing and number of core
tRNA bool whether or not to compute tRNA data
getCAI bool flag to true to retrieve the CAI as well
first int the first most expressed genes to compute the CAI ref statistics
Exceptions
AttributeError "you can't compute codon frequency with Yun's data...", 'not the right From'
UnboundLocalError "you have to load the homologies first"
AttributeError 'not the right From'
   http://rest.ensemblgenomes.org/
Referenced by PyCUB.pyCUB.PyCUB.getHomologylist().
get_evolutionary_distance()
def PyCUB.pyCUB.PyCUB.get_evolutionary_distance (self, display_tree = False, size = 40)
uses metadata of the ancestry tree and computes a theoretical evolutionary distance matrix between each species
can optionaly take any hierarchical evolutionary file between a group of species will populate utils.phylo_distances with a pandas.df of the phylodistance and meandist with the average distance amongst species in the df, species are referenced by their taxon ids. you have to have taxons in your species. will also plot the distance matrix
Parameters
display_tree bool to true to print the phylogenetic tree as a txt (may be quite big)
size int the x size of the plot
Exceptions
EnvironmentError "you need to have R installed to compute the distance"
Referenced by PyCUB.pyCUB.PyCUB.get_taxons().
get_full_genomes()
def PyCUB.pyCUB.PyCUB.get_full_genomes (self, kingdom = 'fungi', seq = 'cds', avg = True, by = "entropy", normalized = False)
go trought all full genome fasta files in the ftp server of ensemblgenomes and
download then parse them to get the full entropy of the genome. usefull for futher comparison steps. will populate the fullentropy, fullvarentropy, fullGCcount, varGCcount of each species where the full sequence is known
Parameters
kingdom str flags the relevant kingdom of you current session [fungi,plants,bacteria, animals]
seq str flags the type of sequence you consider the full genome is (coding or non coding or full) [cds, all, cda]
avg bool to true if we average over each gene or get the full dna in one go.
by str flags what type of computation should be done [entropy,frequency]
normalized should we normalize the entorpy by length
Exceptions
MemoryError "this sequence is too long to be computed (> 1 billion bp)"
Referenced by PyCUB.pyCUB.PyCUB.get_subset().
get_metadata_Ensembl()
def PyCUB.pyCUB.PyCUB.get_metadata_Ensembl (self, kingdoms)
download it and put it where it belongs in the Espece object
parse the server https://fungi.ensembl.org/info/website/ftp/index.html will also get the metadata from the kingdoms that you are analysing
Parameters
kingdoms str flag the type of kingdoms you wanna have 'fungi' 'bacteria' 'plants' 'animals'
Referenced by PyCUB.pyCUB.PyCUB.get_data().
get_mymetadata()
def PyCUB.pyCUB.PyCUB.get_mymetadata (self, From = 'jerem', inpar = True)
Go ahead and design your own metadata retrieval here.
obviously you woud need to change some other functions. for me it is mean protein abundances in cerevisiae cells.
Parameters
From str flag designer of the function to load metadatas
inpar bool for parallel processing
Referenced by PyCUB.pyCUB.PyCUB.get_metadata_Ensembl().
get_subset()
def PyCUB.pyCUB.PyCUB.get_subset (self, homoset, withcopy = False, clusternb = None, species = None, homologies = None)
either changes or returns a subset of the provided homoset
To use once if you want to further refine a set of homologies
Parameters
homoset PyCUB.homoset to get a subset from
withcopy bool to true if we don't want to change the homoset object but create a copy from it
clusternb int set the cluster of the group you want to get need to be between 1 and homogroupnb
homologies list[str] the subset as a list or a tuple of int
species list[the subset as a list, or a list of int
Returns
a HomoSet object (see homoset.py)
Referenced by PyCUB.pyCUB.PyCUB.get_working_homoset().
get_taxons()
def PyCUB.pyCUB.PyCUB.get_taxons (self)
find the taxons of each referenced species (see PyCUB.Espece.gettaxons())
Parameters
None
Referenced by PyCUB.pyCUB.PyCUB.get_full_genomes().
get_working_homoset()
def PyCUB.pyCUB.PyCUB.get_working_homoset (self, clusternb = None, species = None, homologies = None, cleanhomo = None)
create a subset of all_homoset on which you would like to do further computation
To use once you have clustered homology groups, else takes everything. Can also be used just to get a subset of the all homosets.
Parameters
clusternb int set the cluster of the group you want to get need to be between 1 and homogroupnb
homologies list[str] the subset as a list you want to get from all_homoset (can be additional to a clusternb)
species list[str] the subset as a list you want to get from all_homoset (can be additional to a clusternb)
cleanhomo float if the homology is only shared by less than this amount amongst the species present in this homoset, removes them.
Returns
a HomoSet object (see homoset.py)
Exceptions
UnboundLocalError "you have not clusterized you 'all_homoset'. you want to just use 'order_from_matrix' on it."
Referenced by PyCUB.pyCUB.PyCUB.save().
getHomologylist()
def PyCUB.pyCUB.PyCUB.getHomologylist (self, species = 'saccharomyces_cerevisiae', kingdom = 'fungi')
A function to retrieve the homologies directly from a given species.
(it is better to use one of the key species for the different kingdoms (sacharomyces, HS, Arabidopsis..))
Parameters
specie str the name of the specie to get the homology from
kingdom str the kingdom where we can find this specie
Referenced by PyCUB.pyCUB.PyCUB.__init__().
getRelation2G3DD()
def PyCUB.pyCUB.PyCUB.getRelation2G3DD (self, species_name = 'saccharomyces_cerevisiae', kingdom = 'fungi', intrachromosome = "utils/meta/3Dmodel/interactions_HindIII_fdr0.01_intra_cerevisiae.csv", interchromose = ["utils/meta/3Dmodel/cerevisiae_inter1.csv", utils, meta, Dmodel, cerevisiae_inter2, csv, utils, meta, Dmodel, cerevisiae_inter3, csv, utils, meta, Dmodel, cerevisiae_inter4, csv, utils, meta, Dmodel, cerevisiae_inter5, csv, bins = 2000, seq = 'cds', use = 'diament2')
https://www.nature.com/articles/ncomms6876
retrieve the data for the species sacharomyces cerevisiae and Schizosaccharomyces pombe and find if similarity distances of CUB using entropy between genes of this species is predictive of closeness of genes in the nucleus.
Used to confirm a work on nature and see if we can have some similar results by only looking at the CUB
Parameters
species_name str the name of the species to look for
kingdom str the kingdom in which to find the species
intrachromosome str the location of the csv interaction data for intrachromosome respecting the format of the default file
interchromose str the location of the csv interaction data for interchromose respecting the format of the default file
bins int, the number of bin to use (a power of 2)
seq the type of sequence to compare to. (to compute the CUB from)
Referenced by PyCUB.pyCUB.PyCUB.regress_on_genes().
import_metadataTobias()
def PyCUB.pyCUB.PyCUB.import_metadataTobias (self)
will import the metadata obtained from tobias for the fungi species affiliated to cerevisiae to each species for further diagnostics.
Populates metadata[num_genes, plant_pathogen, animal_pathogen, genome_size, plant_symbiotic, brown_rot, white_rot] for each species and weight, mRNA_abundance, is_secreted, protein_abundance, cys_elements, decay_rate for each homology
Parameters
None
Referenced by PyCUB.pyCUB.PyCUB.get_mymetadata().
load()
def PyCUB.pyCUB.PyCUB.load (self, session = None, All = False, filename = 'first500', From = None, by = 'entropy', tRNA = True, inpar = True)
Get the data that is already present on a filename.
Either load from Yun's datasets or from an already saved session. Is being called by get_data. But you can call it to just use one of Yun's files as well
Parameters
From str if this flag is set to 'yun' it means that the filename is made of Yundata in which case we will create directly the homology map in the same time as the rest of the PyCUB object.
All bool set to true if load everything from Yun
by str same flag as get_data (for Yun's files here).
filename str the particular filename when not loading them all
session str if a session name is provided, then will load a zip file from this session's folder
Returns
May return additionals if loading from a session where one decided to save more than the two All/working homologies. to be handled separately
Referenced by PyCUB.pyCUB.PyCUB.get_data(), and PyCUB.pyCUB.PyCUB.import_metadataTobias().
loadmore()
def PyCUB.pyCUB.PyCUB.loadmore (self, filename = 'first500', by = 'entropyLocation')
Get the data that is already present on a filename when you already have data.
is usefull to load more of Yun's datasets. is called when load is set to All
Parameters
From if this flag is set to 'yun' it means that the filename is made of Yundata in which case we will create directly the homology map in the same time as the rest of the PyCUB object. Here it is the only available option.
filename str the filename to additionaly load
by flag same as before
Exceptions
UnboundLocalError "You should try load first, this object is empty"
Referenced by PyCUB.pyCUB.PyCUB.load().
loadspeciestable()
def PyCUB.pyCUB.PyCUB.loadspeciestable (self)
short function to retrieve the speciestable from Disk
Parameters
None
Exceptions
IOError "no speciestable file"
Referenced by PyCUB.pyCUB.PyCUB._undictify().
phylo_distances()
def PyCUB.pyCUB.PyCUB.phylo_distances (self)
a copy of the phylodistances dataframe see (get_evolutionary_distance())
Parameters
None
Returns
a copy of the phylodistances dataframe see (get_evolutionary_distance())
Referenced by PyCUB.pyCUB.PyCUB.compare_species(), and PyCUB.pyCUB.PyCUB.createRefCAI().
plot_distances()
def PyCUB.pyCUB.PyCUB.plot_distances (self, size = 40)
plot the phylogenetic distance matrix
Parameters
size int the x size of the plot
Exceptions
UnboundLocalError "compute the phylo distance matrix first (look at the doc)"
Referenced by PyCUB.pyCUB.PyCUB.get_evolutionary_distance(), and PyCUB.pyCUB.PyCUB.getRelation2G3DD().
regress_on_genes()
def PyCUB.pyCUB.PyCUB.regress_on_genes (self, homoset, full = True, without = ['meanecai', meancai, perctrain = 0.8, algo = "lasso", eps = 0.001, n_alphas = 100)
Will fit a regression curve on the CUB values of the different homologies according to the metadatas available for each of them.
It will try to see if there is enough information in the metadata to retrieve CUB values. and if there is, how much for each metadata (if we constraint the number of regressors) is it better for entropy values, mean entropy or ECAI values or raw frequency, should we remove some data
Parameters
without list[str] of flags [similarity_scores, KaKs_Scores, nans, lenmat, GCcount, weight,
protein_abundance, mRNA_abundance, decay_rate, cys_elements, tot_volume, mean_hydrophobicity,
glucose_cost, synthesis_steps, is_recent, meanecai]
full bool flags to true to use full CUB values or meanCUB values, as regressee
homoset PyCUB.homoset the homoset to use
perctrain the percentage of training set to total set (the rest is used as test set)
algo str flag to lasso or nn to use either Lasso with Cross Validation, or a 2 layer neural net
eps the eps value for the Lasso
n_alphas the number of alphas for the lasso
Returns
scoregenes float, the score of the regression performed
coeffgenes the coefficient applied to each category (for each CUB value if using full)
attrlist the corresponding list[str] of attribute used
Exceptions
UnboundLocalError "wrong params"
Referenced by PyCUB.pyCUB.PyCUB.compare_homologies().
regress_on_species()
def PyCUB.pyCUB.PyCUB.regress_on_species (self, without = [""], full = True, onlyhomo = False, perctrain = 0.8, algo = "lasso", eps = 0.001, n_alphas = 100)
Will fit a regression curve on the CUB values of the different species according to the metadatas available for each of them.
It will try to see if there is enough information in the metadata to retrieve CUB values. and if there is, how much for each metadata (if we constraint the number of regressors) is it better for mean homology CUB or full genome CUB ? or raw frequency, should we remove some data?
Parameters
without list[str] of flags [similarity_scores, KaKs_Scores, nans, lenmat, GCcount, weight,
protein_abundance, mRNA_abundance, decay_rate, cys_elements, tot_volume, mean_hydrophobicity,
glucose_cost, synthesis_steps, is_recent, meanecai]
full bool flags to true to use full CUB values or meanCUB values, as regressee
homoset PyCUB.homoset the homoset to use
perctrain the percentage of training set to total set (the rest is used as test set)
algo str flag to lasso or nn to use either Lasso with Cross Validation, or a 2 layer neural net
eps the eps value for the Lasso
n_alphas the number of alphas for the lasso
Returns
scoregenes float, the score of the regression performed
coeffgenes the coefficient applied to each category (for each CUB value if using full)
attrlist the corresponding list[str] of attribute used
Exceptions
UnboundLocalError "wrong params"
Referenced by PyCUB.pyCUB.PyCUB.compare_species().
save()
def PyCUB.pyCUB.PyCUB.save (self, name, save_workspace = True, save_homo = True, add_homosets = {}, cmdlinetozip = "gzip")
call to save your work.
you should call save on specific data structure if this is what you want to save.
   Will call other object's save, will transform all the variable into dict and save the dicts
   as json files. will save the df also as json files. PyCUB and homoset have
   their own json file.
   adding some params because else the object may be too big
Parameters
name str the name of the particular save on this session
save_workspace bool to fale not to save working_homoset
save_homo bool to false not to save all_homoset
cmdlinetozip str you need to tell the platform how to zip on your system uses gzip by default but it needs to be installed
Referenced by PyCUB.pyCUB.PyCUB.compare_homologies(), PyCUB.pyCUB.PyCUB.compare_species(), and PyCUB.pyCUB.PyCUB.loadmore().
savespeciestable()
def PyCUB.pyCUB.PyCUB.savespeciestable (self)
short function to put the speciestable on Disk
This is done since there may be some memory leakage, probably due to some autoreloading behavior of the global data stored on utils.
Parameters
None
Referenced by PyCUB.pyCUB.PyCUB._undictify().
speciestable()
def PyCUB.pyCUB.PyCUB.speciestable (self)
a copy of the utils.speciestable
Parameters
None
Returns
a copy of the utils.speciestable (dict[int,str] of species to their PyCUB coded value
Referenced by PyCUB.pyCUB.PyCUB.createRefCAI().
The documentation for this class was generated from the following file:
PyCUB/pyCUB.py