PyCUB: Machine exploration of the Codon Usage Bias: PyCUB.espece.Espece Class Reference
PyCUB.espece.Espece Class Reference
docstring for Espece
Public Member Functions
def __init__ (self, kwargs)
can intialize the file from kwargs as a raw dictionnary for json format (output of dictify) or from regular args.
def __str__ (self)
will present some interesting info about this species.
def get_tRNAcopy (self, by="entropy", setnans=False, kingdom='fungi', baseCNvalue=2)
Retrieves tRNA copy numbers from ensembl DB.
def gettaxons (self, kingdom='fungi')
Pars the ensemblgenomes REST API to retrieve the taxons id.
def get_epigenomes (self)
get from ensembl all the data about the epigenome that could help asking interesting questions about the CUB
Public Attributes
name
metadata
is_stored
num_genes
genome_size
Static Public Attributes
code = None
int num_genes = 0
int genome_size = 0
link = None
dictionary metadata
bool is_stored = False
string name = ''
taxonid = None
copynumbers = None
average_entropy = None
average_size = None
var_entropy = None
fullentropy = None
fullvarentropy = None
fullGCcount = None
varGCcount = None
meanGChomo = None
tRNAentropy = None
tot_homologies = None
meanecai = None
Private Member Functions
def _dictify (self)
Used by the saving function.
Detailed Description
docstring for Espece
This is an object that contains all required information of a species for PyCUB and some nice functions to interact for each species
Parameters
code a dict from gene_name to dna_seq string (deprecated)
metadata a dict containing different metadata information that one can gather, preferentially boolean flags to classify the species for plottings and comparings
name the full scientific name of the species is_stored, state if the data is stored in HD (deprecated)
link the link to the ensembl genome
num_genes the number of gene of this species
genome_size the bp size of the coding genome
name the name of the species
taxonid the number assoxiated to this taxon
copynumbers the approx. copynumbers if any of each tRNA known of this species
average_entropy the mean CUB value for each amino acids (CUBD dimension)
average_size the mean size of each homologies
var_entropy the mean of fullvarentropy
fullentropy the array containing all CUB values from the homologies of this species
fullvarentropy the variance for each amino acids of the full CUB values of this species
fullGCcount the GC content of the full coding genome
varGCcount the variance of the GC content of the full coding genome
tRNAentropy the entropy values of the copynumbers of the tRNAs if sufficient tRNAs exist
tot_homologies the total number of homologies to cerevisiae
Member Function Documentation
_dictify()
def PyCUB.espece.Espece._dictify (self) private
Used by the saving function.
transform the object into a dictionary that can be json serializable
Returns
A dict holding every element to be jsonized
Referenced by PyCUB.pyCUB.PyCUB.save().
get_tRNAcopy()
def PyCUB.espece.Espece.get_tRNAcopy (self, by = "entropy", setnans = False, kingdom = 'fungi', baseCNvalue = 2)
Retrieves tRNA copy numbers from ensembl DB.
will print the number of tRNAs and the number of tRNAs with a knwon codons (the usefull ones) will stop and set a trace for the user to inspect the data to do so: please write "dat" in the console. if you see something that should be corrected please do so from the console directly or from the code if there seems to be an error in the code if it is an error in the db that you can't do anything, like a mismatched codon and amino acid, you can't do much. resume the process by typing "c" in the console.
Parameters
species string, the species from which you want the Trna copy number
Returns
Will populate copynumbers. And tRNAentropy if by="entropy" Or will not do anything if the species is unavailable and will print it
Exceptions
AttributeError this is a wrong argument try frequency or entropy
Referenced by PyCUB.espece.Espece.__str__().
gettaxons()
def PyCUB.espece.Espece.gettaxons (self, kingdom = 'fungi')
Pars the ensemblgenomes REST API to retrieve the taxons id.
for the species from which we would not have any (downloaded via Yun for example)
Exceptions
HTTPrequestError not able to connect to the server
Referenced by PyCUB.espece.Espece.get_tRNAcopy().
Member Data Documentation
metadata
dictionary PyCUB.espece.Espece.metadata static
Initial value:
=  {
        "isplant_pathogen": False,
        "isanimal_pathogen": False,
        "isplant_symbiotic": False,  # endophyte or mycorrhizal
        "isbrown_rot": False,
        "iswhite_rot": False
    }
Referenced by PyCUB.espece.Espece.__init__(), PyCUB.espece.Espece.__str__(), and PyCUB.espece.Espece._dictify().
The documentation for this class was generated from the following file:
PyCUB/espece.py