PyCUB: Machine exploration of the Codon Usage Bias: PyCUB.homology.homology Class Reference
PyCUB.homology.homology Class Reference
in homology we store an homology with all its related data,
Public Member Functions
def __init__ (self, kwargs)
def __str__ (self)
def remove (self, species)
removes the list of species from this homology if it exists there
def nb_unique_species (self)
compute the number of unique species in this homologies
def order (self, withtaxons=False)
order the names by numerical increasing order
def compute_averages (self)
Computes the mean, var and mean of the homology.
def reduce_dim (self, alg='tsne', n=2, perplexity=40)
reduce the dimensionality of your gene dataset to a defined dimension using the t-SNE algorithm
def plot (self, reducer="tsne", per=40, interactive=True, D=2, size=20)
plot the dimensionality reduced datapoint of the homology matrix
def clusterize_ (self, clustering='gaussian', eps=0.8, homogroupnb=None, assess=True, verbose=True)
will clusterize the homology using gaussian mixture clustering or DBSCAN
Public Attributes
metrics
homocode
proteinids
protein_abundance
weight
mRNA_abundance
cys_elements
is_secreted
decay_rate
cluster
Static Public Attributes
full = None
var = None
mean = None
clusters = None
centroids = None
dictionary metrics = {}
string homocode = 'None'
nans = None
lenmat = None
names = None
doub = None
GCcount = None
reduced = None
reduced_algo = None
KaKs_Scores = None
similarity_scores = None
list proteinids = []
isrecent = None
ishighpreserved = None
geneids = None
ref = None
refprot = None
refgene = None
ecai = None
meanecai = None
cai = None
meancai = None
int protein_abundance = 0.
int weight = 0
conservation = None
int mRNA_abundance = 0.
int cys_elements = 0
bool is_secreted = False
int decay_rate = 0.
tot_volume = None
mean_hydrophobicity = None
glucose_cost = None
synthesis_steps = None
isoelectricpoint = None
othercods = None
Private Member Functions
def _dictify (self)
Used by the saving function.
Detailed Description
in homology we store an homology with all its related data,
it reduced matrix with dim reduction and its clusters for example it is supposed to be store in a dictionary of homologies an homology is a set of genes from different species related by a common ancester gene and generally a common function. the unique metadatas are generally from the reference species/genome
Parameters
names list of int corresponding to names in utils.speciestable
full np.array[float] (species, amino) of one homology with entropy value vector per species
reduced np.array[float] (species, x*y) of one homology dimensionality reduced
clusters list[int] of cluster val for each species
centroids np.array[float] the position in aminoacid# Dimension of each centroids (number of centroid == number of cluster), dimension is reduced when plotted
metrics a dict of metrics names and values for the cluster of this homology
nans np.array[bool] wether or not this position is a nan
lenmat a np.array[int] species amino of int of length of each amino acids (number)
doub np.array[bool] of wether or not this position is a doublon (a copy number of the gene for the species)
reduced_algo str dimensionality reduction algorithm used on this homology
var np.array of the variance in the CUB value for each datapoint
mean np.array[float] of the mean CUB for each datapoint
homocode str the code of the homology
GCcount np.array[float] GC bias for each datapoint
KaKs_Scores np.array[float] a form of similarity score between genes/datapoints
similarity_scores np.array[float] similarity score between genes/datapoints
proteinids list[str] the protein names for each datapoints
isrecent float a proxy for wether or not this homology has appeated recently
ishighpreserved bool a proxy for wether or not this homology is conserved throughout evolution
geneids list[str] the name of the genes
ref np.array[float] the reference CUB value of cerevisiae gene
refprot str the reference protein name of cerevisiae gene
refgene str the reference gene name of cerevisiae gene
ecai np.array[float] the codon adaptation index of each gene
meanecai float the mean ecai of the ecai
protein_abundance float the average abundance of the protein enoded by this gene in cerevisiae cells
weight int the molecular weight of this protein
mRNA_abundance float the average abundance of the messenger RNA of this coding gene in cerevisiae cells
cys_elements int the number of cys regulatory elements known for cerevisiae on this gene (the value is only referenced for secreted genes)
is_secreted bool wether or not this protein is secreted out of the cell
decay_rate float the half life in minute of this protein
tot_volume int a proxy of the molecular volume of this protein
mean_hydrophobicity a very distant proxy of the hydrophobicity of this protein
glucose_cost the glucose cost of creating the amino acids required to build up this protein
synthesis_steps the number of steps required by the cell to build up the amino acids of this protein
isoelectricpoint float, a proxy of the Pi of this protein.
conservation float, the total conservation of each amino of the corresponding protein
othercods float, the average number of codons other than the ones of the 18 amino acids we are looking at per species on the homology
Member Function Documentation
_dictify()
def PyCUB.homology.homology._dictify (self) private
Used by the saving function.
transform the object into a dictionary that can be json serializable
Parameters
None
Returns
A dict holding every element to be jsonized
Referenced by PyCUB.homology.homology.clusterize_(), and PyCUB.pyCUB.PyCUB.loadmore().
clusterize_()
def PyCUB.homology.homology.clusterize_ (self, clustering = 'gaussian', eps = 0.8, homogroupnb = None, assess = True, verbose = True)
will clusterize the homology using gaussian mixture clustering or DBSCAN
and order them according to the density of each cluster (we are interested in the dense ones) and assess the quality using 3 criterion: BIC, AIC ,silhouette, cal_hara, phylodistance.
Parameters
clustering str flag the clustering algorithm [gaussian, dbscan]
eps float, hyperparam of the max size of the nsphere of each cluster
homogroupnb int hyperparam of gaussian for the number of clusters
assess wether or not to assess the quality of the clustering
verbose wether or not to show clustering quality information
Returns
The clusters for each datapoint of the homology as a list[int]
Exceptions
AttributeError "Hey, please use gaussian or dbscan"
Referenced by PyCUB.homology.homology.plot().
compute_averages()
def PyCUB.homology.homology.compute_averages (self)
Computes the mean, var and mean of the homology.
Parameters
None
Referenced by PyCUB.homology.homology.order().
nb_unique_species()
def PyCUB.homology.homology.nb_unique_species (self)
compute the number of unique species in this homologies
(basically count the number of doub)
Parameters
None
Returns
The number of unique species in this homology
Referenced by PyCUB.homology.homology.remove().
order()
def PyCUB.homology.homology.order (self, withtaxons = False)
order the names by numerical increasing order
and sorts every representations as well according to this ordering
Parameters
withtaxons bool to true if there is taxonomic data (present before preprocessing)
Referenced by PyCUB.homology.homology.nb_unique_species().
plot()
def PyCUB.homology.homology.plot (self, reducer = "tsne", per = 40, interactive = True, D = 2, size = 20)
plot the dimensionality reduced datapoint of the homology matrix
colors represents the different clusters you can set the interactivity to gain deeper knowledge of the dataset. It can dim reduce the data and will also save the figure in utils/save. Moreover, it will print some interesting data about the homology
Parameters
reducer str flag the algorithm to reduce the matrix of utils.cubD to D D
per int he perplexity when using tsne algorithm
size int the size of the plot
interactive (recommended) wether to use bokeh or not to represend the data will show name of the species when hovering over datapoint will show a gradient of evolutionary distance of the species of the datapoint currently hovered to each other species
D int the goal dimension (2-3-4) when using matplotlib
Returns
The plot interactive or not and some informations (as prints)
Exceptions
UnboundLocalError "you need to have dimensionality reduced to 2D to have a right plotting of the centroids"
Referenced by PyCUB.homology.homology.reduce_dim().
reduce_dim()
def PyCUB.homology.homology.reduce_dim (self, alg = 'tsne', n = 2, perplexity = 40)
reduce the dimensionality of your gene dataset to a defined dimension using the t-SNE algorithm
Parameters
alg a matrix of gene codon usage per species
n the desired dimension
perplexity an optional value when you know about tsne
Returns
The reduced dataset
Referenced by PyCUB.homology.homology.compute_averages(), and PyCUB.homology.homology.plot().
remove()
def PyCUB.homology.homology.remove (self, species)
removes the list of species from this homology if it exists there
Parameters
species list[str] of species to remove
Referenced by PyCUB.homoset.HomoSet.compute_entropyloc().
The documentation for this class was generated from the following file:
PyCUB/homology.py